blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/MAY2704/anomaly_detection/discussions
    about: Ask questions about usage or methodology here.
